apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: plm-cluster
  region: ap-northeast-1
  version: "1.22"
managedNodeGroups:
- name: plm-node
  labels:
    alpha.eksctl.io/cluster-name: plm-cluster
    alpha.eksctl.io/nodegroup-name: plm-node
  tags:
    alpha.eksctl.io/nodegroup-name: plm-node
    alpha.eksctl.io/nodegroup-type: managed
  instanceType: t3.medium
  desiredCapacity: 2
  maxSize: 3
  minSize: 1
  iam:
    withAddonPolicies:
      awsLoadBalancerController: true
      autoScaler: true
      cloudWatch: true
